# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.stream_state import StreamState  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, state: StreamState=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param message: The message of this InlineResponse2001.  # noqa: E501
        :type message: str
        :param state: The state of this InlineResponse2001.  # noqa: E501
        :type state: StreamState
        """
        self.swagger_types = {
            'message': str,
            'state': StreamState
        }

        self.attribute_map = {
            'message': 'message',
            'state': 'state'
        }
        self._message = message
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2001.


        :return: The message of this InlineResponse2001.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2001.


        :param message: The message of this InlineResponse2001.
        :type message: str
        """

        self._message = message

    @property
    def state(self) -> StreamState:
        """Gets the state of this InlineResponse2001.


        :return: The state of this InlineResponse2001.
        :rtype: StreamState
        """
        return self._state

    @state.setter
    def state(self, state: StreamState):
        """Sets the state of this InlineResponse2001.


        :param state: The state of this InlineResponse2001.
        :type state: StreamState
        """

        self._state = state
